// src/routes/wallet.routes.js
const express = require('express');
const pool = require('../config/db');
const { requireAuth } = require('../middleware/auth');
const { AppError } = require('../middleware/errorHandler');
const { initMonnifyTransaction } = require('../services/monnify.service');
const { creditWalletForPaymentReference } = require('../services/wallet.service');
const logger = require('../utils/logger');

const router = express.Router();

router.get('/balance', requireAuth, async (req, res) => {
  const result = await pool.query('SELECT wallet_balance FROM users WHERE id = $1', [req.user.id]);
  res.json({ balance: Number(result.rows[0].wallet_balance) });
});

router.get('/transactions', requireAuth, async (req, res) => {
  const result = await pool.query(
    'SELECT * FROM wallet_transactions WHERE user_id = $1 ORDER BY created_at DESC',
    [req.user.id]
  );
  res.json({ transactions: result.rows });
});

router.post('/fund', requireAuth, async (req, res) => {
  const amount = Number((req.body || {}).amount);
  if (!amount || amount < 100) throw new AppError(400, 'Minimum top-up amount is \u20a6100');
  if (amount > 1000000) throw new AppError(400, 'That amount looks too large — please contact support for bulk top-ups');

  const userRes = await pool.query('SELECT * FROM users WHERE id = $1', [req.user.id]);
  const user = userRes.rows[0];
  const paymentReference = `WALLET-${user.id}-${Date.now()}`;
  const redirectUrl = `${req.protocol}://${req.get('host')}/api/wallet/callback?reference=${encodeURIComponent(paymentReference)}`;

  let monnifyResult;
  try {
    monnifyResult = await initMonnifyTransaction({
      amount, customerName: user.full_name, customerEmail: user.email, paymentReference, redirectUrl
    });
  } catch (err) {
    logger.error({ err: err.message }, 'Monnify init failed');
    throw new AppError(502, 'Could not start payment — please try again shortly');
  }

  await pool.query(
    `INSERT INTO wallet_transactions (user_id, type, amount, description, payment_reference, status)
     VALUES ($1, 'credit', $2, 'Wallet top-up', $3, 'pending')`,
    [user.id, amount, paymentReference]
  );

  res.json({ checkoutUrl: monnifyResult.checkoutUrl, paymentReference });
});

// Monnify redirects the customer's browser here after checkout. Not behind
// requireAuth — the browser arrives here directly without our JWT. The
// payment_reference (unique, generated by us) is what ties this back to a
// specific user safely, not anything the visitor supplies.
router.get('/callback', async (req, res) => {
  const reference = req.query.reference;
  const page = (title, body) => res.send(`
    <!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>body{font-family:sans-serif;background:#070F0B;color:#EAF7EE;display:flex;align-items:center;
    justify-content:center;min-height:100vh;margin:0;padding:2rem;text-align:center;}
    .box{max-width:380px;}h1{font-size:1.3rem;}p{color:#7FA08C;}</style></head>
    <body><div class="box"><h1>${title}</h1><p>${body}</p></div></body></html>
  `);

  if (!reference) return page('Something went wrong', 'No payment reference was provided.');

  let result;
  try {
    result = await creditWalletForPaymentReference(reference);
  } catch (err) {
    logger.error({ err: err.message, reference }, 'Wallet callback failed to verify payment');
    return page('Could not confirm payment', 'Please check back in your account shortly — your money is safe either way.');
  }

  if (result.outcome === 'not_found') return page('Something went wrong', 'We could not find that payment.');
  if (result.outcome === 'already_credited') return page('Already credited \u2705', 'This payment was already added to your wallet. You can close this tab.');
  if (result.outcome === 'credited') return page('Payment successful \u2705', 'Your wallet has been credited. Go back to the app and refresh your balance.');
  if (result.outcome === 'failed') return page('Payment not completed', `Status: ${result.paymentStatus}. No funds were added \u2014 feel free to try again.`);
  return page('Payment pending', 'This can take a moment for bank transfers. Check back shortly.');
});

module.exports = router;
